# Generated by Django 3.2.5 on 2021-10-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deseaseDataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('total_cases', models.IntegerField(max_length=100)),
                ('new_cases', models.CharField(max_length=100)),
                ('total_deaths', models.IntegerField(max_length=20)),
                ('new_deaths', models.CharField(max_length=20)),
                ('total_recovered', models.IntegerField(max_length=20)),
                ('new_recovered', models.CharField(max_length=20))
            ],
        ),
    ]
