# Generated by Django 3.2.5 on 2022-02-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_usersymptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersymptoms',
            name='postcode',
            field=models.TextField(default='N22'),
            preserve_default=False,
        ),
    ]
